/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ProdutoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.pro;

/**
 *
 * @author lenovo
 */
public class AreaAdm extends javax.swing.JFrame {

    /**
     * Creates new form AreaAdm
     */
    public AreaAdm() {
        initComponents();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitulo = new javax.swing.JTextField();
        jPreco = new javax.swing.JTextField();
        jAno = new javax.swing.JTextField();
        jDisponivel = new javax.swing.JTextField();
        jDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcadastra = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jAtualizar = new javax.swing.JButton();
        jArtista = new javax.swing.JTextField();
        jMusica = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPromocao = new javax.swing.JTextField();
        jDesconto = new javax.swing.JTextField();
        jGenero = new javax.swing.JTextField();
        jExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTituloActionPerformed(evt);
            }
        });

        jLabel1.setText("titulo");

        jLabel2.setText("preco");

        jLabel3.setText("ano");

        jLabel4.setText("disponivel");

        jLabel5.setText("descriçao");

        jLabel6.setText("promoçao");

        jLabel7.setText("desconto");

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CD1.jpg"))); // NOI18N
        jLabel12.setText("capa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "título", "preco", "ano", "disponivel", "descrição", "artista", "musica", "genero", "promoção", "desconto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jcadastra.setText("cadastrar");
        jcadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcadastraActionPerformed(evt);
            }
        });

        jBuscar.setText("buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jAtualizar.setText("atualizar");
        jAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtualizarActionPerformed(evt);
            }
        });

        jLabel8.setText("artista");

        jLabel9.setText("musica");

        jLabel10.setText("genero");

        jPromocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPromocaoActionPerformed(evt);
            }
        });

        jExcluir.setText("excluir");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        jButton1.setText("CLIENTES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jcadastra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDesconto)
                                            .addComponent(jPreco)
                                            .addComponent(jAno)
                                            .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPromocao))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(162, 162, 162)
                                                .addComponent(jGenero))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jDisponivel)
                                                        .addComponent(jDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel5)
                                                                    .addComponent(jLabel4)))
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(36, 36, 36)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jMusica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                                            .addComponent(jArtista, javax.swing.GroupLayout.Alignment.TRAILING))))))))
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(40, 40, 40)))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcadastra)
                            .addComponent(jBuscar)
                            .addComponent(jAtualizar)
                            .addComponent(jExcluir))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPromocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPromocaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPromocaoActionPerformed

    private void jTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTituloActionPerformed

    private void jAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtualizarActionPerformed
        // TODO add your handling code here:
        String titulo = jTitulo.getText();
        String preco = jPreco.getText();
        String ano = jAno.getText();
        String promocao = jPromocao.getText();
        String desconto = jDesconto.getText();
        String descricao = jDescricao.getText();
        String disponivel = jDisponivel.getText();
        String capa = jTitulo.getText();
        String artista = jArtista.getText();
        String musica = jMusica.getText();
        String genero = jGenero.getText();
        if("".equals(titulo) || "".equals(preco) || "".equals(ano) || "".equals(promocao)
            || "".equals(descricao) || "".equals(disponivel)){
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos");
        }else{
            pro p = new pro();

            p.setCapa(titulo);
            p.setTitulo(titulo);
            p.setPreco(preco);
            p.setAnoLancamento(ano);
            p.setPromocao(promocao);
            p.setDesconto(desconto);
            p.setDescricao(descricao);
            p.setDisponibilidade(disponivel);
            p.setArtista(artista);
            p.setMusica(musica);
            p.setId_genero(1);
            p.setId_cd((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            ProdutoDAO bd= new ProdutoDAO();
            bd.atualizar_Pro(p);
            atualizarTabela();
            JOptionPane.showMessageDialog(null, "cd atualizado com sucesso");
            limpar();
        }
    }//GEN-LAST:event_jAtualizarActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jcadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcadastraActionPerformed
        String titulo = jTitulo.getText();
        String preco = jPreco.getText();
        String ano = jAno.getText();
        String promocao = jPromocao.getText();
        String desconto = jDesconto.getText();
        String descricao = jDescricao.getText();
        String disponivel = jDisponivel.getText();
        String capa = jTitulo.getText();
        String artista = jArtista.getText();
        String musica = jMusica.getText();
        String genero = jGenero.getText();
        if("".equals(titulo) || "".equals(preco) || "".equals(ano) || "".equals(promocao)
            || "".equals(descricao) || "".equals(disponivel)){
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos");
        }else{
            pro p = new pro();

            p.setCapa(titulo);
            p.setTitulo(titulo);
            p.setPreco(preco);
            p.setAnoLancamento(ano);
            p.setPromocao(promocao);
            p.setDesconto(desconto);
            p.setDescricao(descricao);
            p.setDisponibilidade(disponivel);
            p.setArtista(artista);
            p.setMusica(musica);
            p.setId_genero(1);
            ProdutoDAO bd= new ProdutoDAO();
            bd.inserir_Pro(p);
            atualizarTabela();
            JOptionPane.showMessageDialog(null, "cd cadastrado com sucesso");
            limpar();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jcadastraActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!= -1){
            jTitulo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jPreco.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jAno.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            jDisponivel.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            jDescricao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            jArtista.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            jMusica.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            jGenero.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            jPromocao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            jDesconto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!= -1){
            jTitulo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jPreco.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jAno.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            jDisponivel.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            jDescricao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            jArtista.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            jMusica.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            jGenero.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            jPromocao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            jDesconto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!= -1){
            pro p = new pro();
            p.setId_cd((int)jTable1.getValueAt(jTable1.getSelectedRow(),0));
            ProdutoDAO bd = new ProdutoDAO();
            bd.excluir_pro(p);
            atualizarTabela();
            limpar();
        }
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new TabClie().setVisible(true);
                            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
                            dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaAdm().setVisible(true);
            }
        });
    }
    public void limpar(){
    
    jTitulo.setText("");
        jPreco.setText("");
        jAno.setText("");
        jDisponivel.setText("");
        jDescricao.setText("");
        jArtista.setText("");
        jMusica.setText("");
        jGenero.setText("");
        jPromocao.setText("");
        jDesconto.setText("");
    }
    public void atualizarTabela(){
      DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
      modelo.setNumRows(0);
      ProdutoDAO bd = new ProdutoDAO();
      List <pro> listar= bd.listar_Pro();
      for(pro p : listar){
      modelo.addRow(new Object[]{
      p.getId_cd(),
      p.getTitulo(),
      p.getPreco(),
      p.getAnoLancamento(),
      p.getDisponibilidade(),
      p.getDescricao(),
      p.getArtista(),
      p.getMusica(),
      p.getId_genero(),
      p.getPromocao(),
      p.getDesconto()
      });
              
      }
  
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAno;
    private javax.swing.JTextField jArtista;
    private javax.swing.JButton jAtualizar;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jDesconto;
    private javax.swing.JTextField jDescricao;
    private javax.swing.JTextField jDisponivel;
    private javax.swing.JButton jExcluir;
    private javax.swing.JTextField jGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMusica;
    private javax.swing.JTextField jPreco;
    private javax.swing.JTextField jPromocao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTitulo;
    private javax.swing.JButton jcadastra;
    // End of variables declaration//GEN-END:variables
}
