/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.AcessoDAO;
import javax.swing.JOptionPane;
import metodos.pro;

/**
 *
 * @author lenovo
 */
public class login extends javax.swing.JFrame {

    private AreaClie clie;

    /**
     * Creates new form AdmControl
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlogar = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        cBlog = new javax.swing.JComboBox<>();
        jLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSenha = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlogar.setText("entra");
        Jlogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JlogarActionPerformed(evt);
            }
        });
        getContentPane().add(Jlogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, 30));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 260, 20));

        cBlog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADIMINISTRADOR", "CLIENTE" }));
        cBlog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cBlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBlogActionPerformed(evt);
            }
        });
        getContentPane().add(cBlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 180, 30));

        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 260, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 50, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, 30));
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 70, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginActionPerformed

    private void cBlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBlogActionPerformed

    }//GEN-LAST:event_cBlogActionPerformed

    private void JlogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JlogarActionPerformed

        if( cBlog.getSelectedItem().equals("ADIMINISTRADOR")){
            String login= jLogin.getText();
            String senha= jSenha.getText();
            AcessoDAO sql = new AcessoDAO();
            if("".equals(login) && "".equals(senha)){
                JOptionPane.showMessageDialog(this, "Preencha os campos corretamente");
            }else{
                if(sql.LogarAdm(login, senha) == true){
                    new Thread(){
                        public void run(){
                            for (int i=0; i<101; i++){
                                jProgressBar1.setValue(i);
                                try{
                                    Thread.sleep(35);
                                } catch (Exception ex) {
                                    ex.getMessage();
                                }

                            }
                            new AreaAdm().setVisible(true);
                            dispose();
                        }
                    }.start();
                } else{
                    JOptionPane.showMessageDialog(this, "Usuário inexistente");
                }
            }
        }else if( cBlog.getSelectedItem().equals("CLIENTE")){
            String login= jLogin.getText();
            String senha= jSenha.getText();
            AcessoDAO sql = new AcessoDAO();
            if("".equals(login) && "".equals(senha)){
                JOptionPane.showMessageDialog(this, "Preencha os campos");
            }else{
                if(sql.LogarClie(login, senha) == true){
                    new Thread(){
                        public void run(){
                            for (int i=0; i<101; i++){
                                jProgressBar1.setValue(i);
                                try{
                                    Thread.sleep(35);
                                } catch (Exception ex) {
                                    ex.getMessage();
                                }

                            }
                            new AreaClie().setVisible(true);
                            dispose();
                        }
                    }.start();
                } else{
                    JOptionPane.showMessageDialog(this, "Usuario inesistente");
                }
            }
    }//GEN-LAST:event_JlogarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jlogar;
    private javax.swing.JComboBox<String> cBlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPasswordField jSenha;
    // End of variables declaration//GEN-END:variables

}

